### ISSUE TITLE
[Feature Request]: Javascript Implementation 

### ISSUE THREAD

**Issue by gynet** [cryptomator/cryptolib#10]
Is there any plan for a client or just a simple lib implemented in Javascript? It would be help a lot for usability and conveniency purpose.

**Comment by CiriousJoker** [comment]
I second that. Theoretically, it should be enough to compile the necessary java sourcecode via [JWebAssembly](https://github.com/i-net-software/JWebAssembly#exporting-functions) by annotating exportable functions

**Comment by CiriousJoker** [comment]
@overheadhunter Are there any plans to support something like this?

**Comment by overheadhunter** [comment]
> @overheadhunter Are there any plans to support something like this?

No capacity atm. But glad to assist with questions, if someone wants to give it a try.

**Comment by Loveprotooyou** [comment]
ok

**Comment by CiriousJoker** [comment]
@overheadhunter 

I'm not able to compile the encryption library into a .class file. Do you happen to have one lying around or could press compile real quick?

I would then try to compile this .class file to .js via [TeaVM](http://teavm.org/).

**Comment by overheadhunter** [comment]
Well the library consists of a shitload of classes. I can not compile them into _one_ class file. Maybe it is even easier to write a webassembly based on our [cryptomator-objc-cryptor](https://github.com/cryptomator/cryptomator-objc-cryptor)...

But all this sounds a lot more difficult to me than using the Web Crypto API... :thinking:

**Comment by overheadhunter** [comment]
Let's say I'd write a js library for content and name decryption. Content decryption is not really a problem, but the file names are tricky: In order to decrypt a filename you would have to pass the encrypted name (obviously), the key (obviously) and the directory id (less obvious) to the decryptName() function.

Are you familiar with our [directory structure](https://docs.cryptomator.org/en/latest/security/architecture/#filename-encryption)? You need to make sure to go to the correct ciphertext directory after retrieving the directory id. I can imagine this is very tricky since each cloud web interface behaves differently.

Maybe a JS version would only be working for websites that have a url parameter for the path to browse, such as `examplecloud.com/files?path=foo/bar/baz`

**Comment by CiriousJoker** [comment]
Well you would have to make use of for example storage provider api to get a full path.

A js library that provides these two things should actually be enough imo.

**Comment by gynet** [comment]
I think to use WebCryptoAPI  should be the way to go

**Comment by ashutoshsaboo** [comment]
Huge +1 on this. Is this being still considered @overheadhunter ? One of the issues with Cryptomator is not being able to access the encrypted files on a browser, which native encrypted cloud storage providers provide for. Let's say if I have a vault and I need to access it on a foreign device for immediate access, then setting up the client locally wouldn't be possible right? As a matter of fact even setting up Cyberduck might not be the most secure solution, as we don't necessarily trust that device. 

Having capability to access Cryptomator vaults via a web app in browsers, would be an extremely useful thing to have for accessibility and portability from anywhere and everywhere, and almost give a native experience like the other cloud storage providers provide for. 

If it helps, here are some related WIP implementations that I came across as I was searching for such a thing - https://github.com/marcboeker/cryptomator , https://github.com/awendland/cryptomator-js-unofficial .

**Comment by infeo** [comment]
A JS implementation can be considered, when there will be new major crpytofs version/Cryptomator encryption scheme. In its current form, this is not planned.
